### ISSUE TITLE
question about used in mobile devices (android)

### ISSUE THREAD

**Issue by ritox842** [dropbox/lepton#29] opened 2016-07-18 07:48 UTC
Is it possible to run this tool on native mobile apps?
I want to use it to compress user photos before sending them to the server ..

**Comment by danielrh** [comment] 2016-07-18 08:29
Duplicate of https://github.com/dropbox/lepton/issues/13
Great question! We'll get it working soon--with that library it shouldn't be that much work..someone would just need to have access to a mobile dev kit

**Closed by danielrh** 2016-07-18 08:29 UTC
